import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Image from "next/image";
import logo from '@/images/light-icons/android-chrome-192x192.png';

export const metadata: Metadata = {
    title: "hondana",
    description: "Generated by create next app",

};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`h-screen max-h-screen grid bg-emerald-50 dark:bg-emerald-900`}>
            <header>
                <a href="/"
                   className="flex items-center p-1 gap-1 border-solid border-b-2 border-emerald-950 bg-emerald-700">
                    <Image src={logo}
                           width={48}
                           height={48}
                           alt="logo"/>
                    <p className="text-2xl w-full font-extrabold text-emerald-50">hondana</p>
                </a>
            </header>

            <main className="grid max-h-full h-full overflow-hidden ">

                <Sidebar/>

                <article className="p-2 overflow-y-auto">
                    {children}
                </article>
            </main>
        </body>
        </html>
    );
}
